wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encyclopedias"

urlpatterns = [
    path("", views.index, name="index"),
    #path("wiki/CSS", views.CSS, name="CSS"),
    path("wiki/<str:entry_name>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:entry_name>", views.edit, name="edit"),
    path("random_entry/", views.random_entry, name="random_entry")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import markdown2
from django.http import HttpResponse
from django.shortcuts import render
from django import forms
import random
from . import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry_name):
    found_entry = util.get_entry(entry_name)
    if found_entry != None:
        md = markdown2.Markdown()
        found_entry = md.convert(found_entry)
        return render(request, "encyclopedia/entry.html",{
            "entry_name":entry_name,
            "found_entry":found_entry
        })
    else:
        return render(request, "encyclopedia/not_found.html",{
            "entry_name":entry_name
        })

def search(request):
    entry_search = request.GET.get('q')
    entries = util.list_entries()
    entries_lower = [x.lower() for x in entries]
    matchedEntries = []
    for entry in entries_lower:
        if entry_search.lower() in entry:
            id_matched_entry=entries_lower.index(entry)
            matchedEntries.append(entries[id_matched_entry])
    if (entry_search.lower() in entries_lower):
        found_entry = util.get_entry(entry_search)
        md = markdown2.Markdown()
        found_entry = md.convert(found_entry)
        return render(request, "encyclopedia/entry.html",{
            "entry_name":entry_search,
            "found_entry":found_entry
        })
    elif matchedEntries:
        return render(request, "encyclopedia/not_found.html",{
            "matched":matchedEntries,
            "entry_name":entry_search
        })
    else:
        return render(request, "encyclopedia/not_found.html",{
            "matched":False,
            "entry_name":entry_search
        })

def create(request):
    if (request.method=="GET"):
        if(request.GET.get('create')):
            print(request.GET.get('create'))
            create_title=request.GET.get('create') 
            print(create_title)
            create_title=create_title.lstrip("Create")
            create_title=create_title.lstrip(" ")
            print(create_title)
            return render(request, "encyclopedia/create.html",{
                "entry_name" : create_title
            })
        else:
            return render(request, "encyclopedia/create.html")
    else:
        entries = util.list_entries()
        entries = [x.lower() for x in entries]
        existe=False
        new_title=request.POST["title"].lower()
        for entry in entries:
            if entry == new_title:
                existe=True
        if existe:
            print("Ya existe ese titulo")
            return render(request, "encyclopedia/already_exists.html",{
                "entry_name":new_title
            })
        else:
            content="#"+request.POST["title"]+'\n'+request.POST["content"]
            content=content.encode('utf-8')
            util.save_entry(request.POST["title"], content)
            found_entry = util.get_entry(request.POST["title"])
            md = markdown2.Markdown()
            found_entry = md.convert(found_entry)
            return render(request, "encyclopedia/entry.html",{
                "entry_name" : request.POST["title"],
                "found_entry" : found_entry
            })

def edit(request, entry_name):
    if(request.method=="GET"):
        print(request.GET)
        found_entry = util.get_entry(entry_name)
        return render(request, "encyclopedia/edit.html", {
            "title" : entry_name,
            "content" : found_entry
        })  
    else:
        print(request.POST["title"])
        print(request.POST["content"])
        content=request.POST["content"]
        content=content.encode('utf-8')
        util.save_entry(request.POST["title"], content)
        found_entry = util.get_entry(request.POST["title"])
        md = markdown2.Markdown()
        found_entry = md.convert(found_entry)        
        return render(request, "encyclopedia/entry.html",{
                "entry_name" : request.POST["title"],
                "found_entry" : found_entry
        })  

def random_entry(request):
    entries = util.list_entries()
    entry_random = random.choice(entries)
    found_entry = util.get_entry(entry_random)
    md = markdown2.Markdown()
    found_entry = md.convert(found_entry)        
    return render(request, "encyclopedia/entry.html",{
        "entry_name" : entry_random,
        "found_entry" : found_entry
    })  

wiki/encyclopedia/templates/encyclopedia/already_exists.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_name }} already exists
{% endblock %}

{% block body %}

    <h1>Error </h1>
    
    <p>The entry <b>{{ entry_name }}</b> already exists.</p>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}

    <h1>Create New Page</h1>

    <form action="{% url 'encyclopedias:create' %}" method="POST">
        {% csrf_token %}
        Title wiki
        </br>
        {% if entry_name %}
            <input type="text" name="title" value="{{ entry_name }}">
        {% else %}
            <input type="text" name="title" >
        {% endif %}
        </br>
        Content wiki
        </br>
        <textarea   name="content"></textarea>
        </br>
        </br>
        <input type="submit" value="Save">
    </form>
    <!--{{form.title_wiki.label}}
    </br>
    {{form.title_wiki}}
    </br>
    {{form.content_wiki.label}}
    </br>
    {{form.content_wiki}}
    </br>
    </br>
    <input type="submit" value="Save">-->

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }} 
{% endblock %}

{% block body %}

    <h1>Edit {{ title }} </h1>

    <form action="{% url 'encyclopedias:edit' entry_name=title %}" method="POST">
        {% csrf_token %}
        Content wiki
        </br>        
        <input type="text" name="title" hidden value="{{ title }}">
        <textarea   name="content">{{ content }}</textarea>
        </br>
        </br>
        <input type="submit" value="Save">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_name }}
{% endblock %}

{% block body %}

            {{ found_entry|safe }}

            <a  href="/edit/{{entry_name|safe}}">Edit</a>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{entry|safe}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar">
                <h2>Wiki</h2>
                <form method="GET" action="{% url 'encyclopedias:search' %}">
                    <!--{% csrf_token %}-->
                    <input type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedias:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedias:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedias:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_name }} not found
{% endblock %}

{% block body %}
    
    {% if matched  %}

        <h1>Search results for "{{ entry_name }}"</h1>
                
        
        <ul>
            {% for match in matched %}
                <li><a href="/wiki/{{match|safe}}">{{ match }}</a></li>
            {% endfor %}
        </ul>
        
        <!--a  href="/create/{{entry_name|safe}}">Create</a-->

    {% else %}

        <h1>404 Page not found</h1>
                
        <p>The entry <b>{{ entry_name }}</b> doesn't exist.</p>
        
        <!--form action="{% url 'encyclopedias:create' %}" method="POST">
            {% csrf_token %}
            <a  href="/create">Create</a>
        </form-->

        <form action="{% url 'encyclopedias:create'  %}" method="GET">
            
            <input name="create" type="submit" value="Create {{entry_name}}">
        </form>


    {% endif %}

{% endblock %}